import type { Request, Response } from 'express'

export type Product = {
  id: number
  title: string
  description: string
  price: number
  discountPercentage: number
  rating: number
  stock: number
  brand: string
  category: string
  thumbnail: string
  images: string[]
}

const u = (url: string) => 'https://wsrv.nl/?url=' + encodeURIComponent(url);

const customProducts: Product[] = [
  // Smartphones
  { id: 1001, title: 'Apple iPhone 15 Pro Max', brand: 'Apple', category: 'smartphones', price: 1199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg')], description: 'Latest Apple smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1002, title: 'Samsung Galaxy S24 Ultra', brand: 'Samsung', category: 'smartphones', price: 1299, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928-1.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928-1.jpg')], description: 'Latest Samsung smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1003, title: 'Google Pixel 8 Pro', brand: 'Google', category: 'smartphones', price: 999, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg')], description: 'Latest Google smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1004, title: 'OnePlus 12', brand: 'OnePlus', category: 'smartphones', price: 799, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg')], description: 'Latest OnePlus smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1005, title: 'Xiaomi 14 Ultra', brand: 'Xiaomi', category: 'smartphones', price: 1099, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg')], description: 'Latest Xiaomi smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1006, title: 'Sony Xperia 1 V', brand: 'Sony', category: 'smartphones', price: 1399, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-v.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-v.jpg')], description: 'Latest Sony smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1007, title: 'Samsung Galaxy Z Fold 5', brand: 'Samsung', category: 'smartphones', price: 1799, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold5-5g.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold5-5g.jpg')], description: 'Latest Samsung smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1008, title: 'Nothing Phone (2)', brand: 'Nothing', category: 'smartphones', price: 599, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/nothing-phone2.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/nothing-phone2.jpg')], description: 'Latest Nothing smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1009, title: 'Asus ROG Phone 8 Pro', brand: 'Asus', category: 'smartphones', price: 1199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg')], description: 'Latest Asus smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1010, title: 'Motorola Edge 50 Pro', brand: 'Motorola', category: 'smartphones', price: 699, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-pro.jpg')], description: 'Latest Motorola smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1011, title: 'Apple iPhone 14 Pro', brand: 'Apple', category: 'smartphones', price: 999, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg')], description: 'Latest Apple smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1012, title: 'Samsung Galaxy A55', brand: 'Samsung', category: 'smartphones', price: 499, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg')], description: 'Latest Samsung smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1013, title: 'Vivo X100 Pro', brand: 'Vivo', category: 'smartphones', price: 899, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/vivo-x100-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/vivo-x100-pro.jpg')], description: 'Latest Vivo smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1014, title: 'Xiaomi 13 Pro', brand: 'Xiaomi', category: 'smartphones', price: 649, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/xiaomi-13-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/xiaomi-13-pro.jpg')], description: 'Latest Xiaomi smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  { id: 1015, title: 'Realme 12 Pro+', brand: 'Realme', category: 'smartphones', price: 499, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg')], description: 'Latest Realme smartphone.', discountPercentage: 12, rating: 4.8, stock: 150 },
  
  // Laptops
  { id: 2001, title: 'Apple MacBook Pro 16 (M3)', brand: 'Apple', category: 'laptops', price: 3499, thumbnail: u('store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spaceblack-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1698169223815'), images: [u('store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-spaceblack-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1698169223815')], description: 'Powerful Apple laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2002, title: 'Dell XPS 14', brand: 'Dell', category: 'laptops', price: 1699, thumbnail: u('i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/14-9440/media-gallery/silver/touch/notebook-xps-14-9440-t-slv-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=536&qlt=100,1&resMode=sharp2&size=536,402&chrss=full'), images: [u('i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/14-9440/media-gallery/silver/touch/notebook-xps-14-9440-t-slv-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=536&qlt=100,1&resMode=sharp2&size=536,402&chrss=full')], description: 'Powerful Dell laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2003, title: 'Lenovo ThinkPad X1 Carbon', brand: 'Lenovo', category: 'laptops', price: 1899, thumbnail: u('p1-ofp.static.pub//fes/cms/2024/02/21/j5p9v87z57w1c9v6q2l5f9k4s8m0h1493035.png'), images: [u('p1-ofp.static.pub//fes/cms/2024/02/21/j5p9v87z57w1c9v6q2l5f9k4s8m0h1493035.png')], description: 'Powerful Lenovo laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2004, title: 'ASUS ROG Zephyrus G14', brand: 'Asus', category: 'laptops', price: 1599, thumbnail: u('dlcdnwebimgs.asus.com/gain/9C22B43D-4F18-479D-A33A-E6E60706F79F/w250'), images: [u('dlcdnwebimgs.asus.com/gain/9C22B43D-4F18-479D-A33A-E6E60706F79F/w250')], description: 'Powerful Asus laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2005, title: 'Apple MacBook Air 15 (M3)', brand: 'Apple', category: 'laptops', price: 1299, thumbnail: u('store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-midnight-select-202306?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1684518479433'), images: [u('store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-midnight-select-202306?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1684518479433')], description: 'Powerful Apple laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2006, title: 'HP Spectre x360 14', brand: 'HP', category: 'laptops', price: 1499, thumbnail: u('ssl-product-images.www8-hp.com/digmedialib/prodimg/mut_assets/cg_400x400/c08920173.png'), images: [u('ssl-product-images.www8-hp.com/digmedialib/prodimg/mut_assets/cg_400x400/c08920173.png')], description: 'Powerful HP laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2007, title: 'Razer Blade 16', brand: 'Razer', category: 'laptops', price: 2999, thumbnail: u('assets3.razerzone.com/p0k5A8P3u9sD3r2H0k6G4x5y1bE=/300x300/https%3A%2F%2Fhybrismediacp.razerzone.com%2Fsys_master%2Froot%2Fh9a%2Fh6a%2F9676643205150%2Frazer-blade-16-2024-mercury-500x500.png'), images: [u('assets3.razerzone.com/p0k5A8P3u9sD3r2H0k6G4x5y1bE=/300x300/https%3A%2F%2Fhybrismediacp.razerzone.com%2Fsys_master%2Froot%2Fh9a%2Fh6a%2F9676643205150%2Frazer-blade-16-2024-mercury-500x500.png')], description: 'Powerful Razer laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2008, title: 'Microsoft Surface Laptop 7', brand: 'Microsoft', category: 'laptops', price: 1199, thumbnail: u('img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RW1k0GZ?ver=9c4a'), images: [u('img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RW1k0GZ?ver=9c4a')], description: 'Powerful Microsoft laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2009, title: 'LG Gram 14', brand: 'LG', category: 'laptops', price: 1299, thumbnail: u('www.lg.com/us/images/laptops/md06253456/gallery/desktop-01.jpg'), images: [u('www.lg.com/us/images/laptops/md06253456/gallery/desktop-01.jpg')], description: 'Powerful LG laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2010, title: 'Acer Zenbook S 13 OLED', brand: 'Acer', category: 'laptops', price: 1099, thumbnail: u('dlcdnwebimgs.asus.com/gain/F3C1853B-3286-4554-94E5-3ED5F78A8DBB/w250'), images: [u('dlcdnwebimgs.asus.com/gain/F3C1853B-3286-4554-94E5-3ED5F78A8DBB/w250')], description: 'Powerful Acer laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2011, title: 'Alienware m16 R2', brand: 'Alienware', category: 'laptops', price: 1699, thumbnail: u('i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienware-m16-r2-amd/media-gallery/laptop-alienware-m16-r2-bk-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=536&qlt=100,1&resMode=sharp2&size=536,402&chrss=full'), images: [u('i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienware-m16-r2-amd/media-gallery/laptop-alienware-m16-r2-bk-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=536&qlt=100,1&resMode=sharp2&size=536,402&chrss=full')], description: 'Powerful Alienware laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2012, title: 'MSI Stealth 14 Studio', brand: 'MSI', category: 'laptops', price: 1499, thumbnail: u('asset.msi.com/resize/image/global/product/product_1672304724a8fc3a2d2fb40cc889f816b1df36d2c4.png62405b38c58fe0f07fcef2367d8a9ba1/400.png'), images: [u('asset.msi.com/resize/image/global/product/product_1672304724a8fc3a2d2fb40cc889f816b1df36d2c4.png62405b38c58fe0f07fcef2367d8a9ba1/400.png')], description: 'Powerful MSI laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2013, title: 'Gigabyte AERO 14 OLED', brand: 'Gigabyte', category: 'laptops', price: 1399, thumbnail: u('www.gigabyte.com/FileUpload/Global/KeyFeature/2253/innerimages/gallery/aero-14-oled-gallery-01.png'), images: [u('www.gigabyte.com/FileUpload/Global/KeyFeature/2253/innerimages/gallery/aero-14-oled-gallery-01.png')], description: 'Powerful Gigabyte laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2014, title: 'Samsung Galaxy Book 4 Pro', brand: 'Samsung', category: 'laptops', price: 1449, thumbnail: u('images.samsung.com/is/image/samsung/p6pim/in/np940xgq-kg1in/gallery/in-galaxy-book4-pro-14-inch-np940-np940xgq-kg1in-539829285?$650_519_PNG$'), images: [u('images.samsung.com/is/image/samsung/p6pim/in/np940xgq-kg1in/gallery/in-galaxy-book4-pro-14-inch-np940-np940xgq-kg1in-539829285?$650_519_PNG$')], description: 'Powerful Samsung laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  { id: 2015, title: 'Framework Laptop 13', brand: 'Framework', category: 'laptops', price: 1049, thumbnail: u('frame.work/assets/home/laptop-13-39d2e1c66df0443d34e622f462e086f6a72e81fc0f06a0149e9e1f5ab997184e.png'), images: [u('frame.work/assets/home/laptop-13-39d2e1c66df0443d34e622f462e086f6a72e81fc0f06a0149e9e1f5ab997184e.png')], description: 'Powerful Framework laptop.', discountPercentage: 10, rating: 4.7, stock: 120 },
  
  // Tablets
  { id: 3001, title: 'Apple iPad Pro 13 (M4)', brand: 'Apple', category: 'tablets', price: 1299, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-13-2024.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-13-2024.jpg')], description: 'Versatile Apple tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3002, title: 'Samsung Galaxy Tab S9 Ultra', brand: 'Samsung', category: 'tablets', price: 1199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-ultra-5g.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-ultra-5g.jpg')], description: 'Versatile Samsung tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3003, title: 'Apple iPad Air 11 (M2)', brand: 'Apple', category: 'tablets', price: 599, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-11-2024.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-11-2024.jpg')], description: 'Versatile Apple tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3004, title: 'Google Pixel Tablet', brand: 'Google', category: 'tablets', price: 499, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/google-pixel-tablet.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/google-pixel-tablet.jpg')], description: 'Versatile Google tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3005, title: 'OnePlus Pad', brand: 'OnePlus', category: 'tablets', price: 499, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/oneplus-pad.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/oneplus-pad.jpg')], description: 'Versatile OnePlus tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3006, title: 'Samsung Galaxy Tab S9 FE', brand: 'Samsung', category: 'tablets', price: 449, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-fe.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-fe.jpg')], description: 'Versatile Samsung tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3007, title: 'Lenovo Tab P12 Pro', brand: 'Lenovo', category: 'tablets', price: 599, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/lenovo-tab-p12-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/lenovo-tab-p12-pro.jpg')], description: 'Versatile Lenovo tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3008, title: 'Apple iPad mini (2021)', brand: 'Apple', category: 'tablets', price: 499, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-2021.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-2021.jpg')], description: 'Versatile Apple tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3009, title: 'Xiaomi Pad 6', brand: 'Xiaomi', category: 'tablets', price: 399, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/xiaomi-pad-6.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/xiaomi-pad-6.jpg')], description: 'Versatile Xiaomi tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3010, title: 'Xiaomi Redmi Pad SE', brand: 'Xiaomi', category: 'tablets', price: 199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-pad-se.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-pad-se.jpg')], description: 'Versatile Xiaomi tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3011, title: 'Amazon Fire Max 11', brand: 'Amazon', category: 'tablets', price: 229, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/amazon-fire-max-11.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/amazon-fire-max-11.jpg')], description: 'Versatile Amazon tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3012, title: 'Lenovo Tab M11', brand: 'Lenovo', category: 'tablets', price: 199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m11.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m11.jpg')], description: 'Versatile Lenovo tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3013, title: 'Honor Pad 9', brand: 'Honor', category: 'tablets', price: 349, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/honor-pad-9.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/honor-pad-9.jpg')], description: 'Versatile Honor tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3014, title: 'Vivo Pad 3 Pro', brand: 'Vivo', category: 'tablets', price: 449, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/vivo-pad3-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/vivo-pad3-pro.jpg')], description: 'Versatile Vivo tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  { id: 3015, title: 'Realme Pad 2', brand: 'Realme', category: 'tablets', price: 249, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/realme-pad-2.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/realme-pad-2.jpg')], description: 'Versatile Realme tablet.', discountPercentage: 15, rating: 4.6, stock: 180 },
  
  // Smartwatches
  { id: 4001, title: 'Apple Watch Ultra 2', brand: 'Apple', category: 'smartwatches', price: 799, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-watch-ultra-2.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-watch-ultra-2.jpg')], description: 'Advanced Apple smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4002, title: 'Samsung Galaxy Watch 6 Classic', brand: 'Samsung', category: 'smartwatches', price: 399, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch6-classic.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch6-classic.jpg')], description: 'Advanced Samsung smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4003, title: 'Garmin Epix Pro (Gen 2)', brand: 'Garmin', category: 'smartwatches', price: 899, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/garmin-epix-pro-gen2.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/garmin-epix-pro-gen2.jpg')], description: 'Advanced Garmin smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4004, title: 'Google Pixel Watch 2', brand: 'Google', category: 'smartwatches', price: 349, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/google-pixel-watch-2.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/google-pixel-watch-2.jpg')], description: 'Advanced Google smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4005, title: 'Apple Watch Series 9', brand: 'Apple', category: 'smartwatches', price: 399, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-watch-series-9.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-watch-series-9.jpg')], description: 'Advanced Apple smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4006, title: 'OnePlus Watch 2', brand: 'OnePlus', category: 'smartwatches', price: 299, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/oneplus-watch-2.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/oneplus-watch-2.jpg')], description: 'Advanced OnePlus smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4007, title: 'Garmin Venu 3', brand: 'Garmin', category: 'smartwatches', price: 449, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/garmin-venu-3.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/garmin-venu-3.jpg')], description: 'Advanced Garmin smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4008, title: 'Amazfit GTR 4', brand: 'Amazfit', category: 'smartwatches', price: 199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/amazfit-gtr-4.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/amazfit-gtr-4.jpg')], description: 'Advanced Amazfit smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4009, title: 'Samsung Galaxy Watch 6', brand: 'Samsung', category: 'smartwatches', price: 299, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch6.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch6.jpg')], description: 'Advanced Samsung smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4010, title: 'Apple Watch SE (2022)', brand: 'Apple', category: 'smartwatches', price: 249, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/apple-watch-se-2022.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/apple-watch-se-2022.jpg')], description: 'Advanced Apple smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4011, title: 'Huawei Watch 4 Pro', brand: 'Huawei', category: 'smartwatches', price: 549, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/huawei-watch-4-pro.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/huawei-watch-4-pro.jpg')], description: 'Advanced Huawei smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4012, title: 'Noise ColorFit Pro 5', brand: 'Noise', category: 'smartwatches', price: 59, thumbnail: u('cdn.shopify.com/s/files/1/0997/6284/files/Colorfit_Pro_5.jpg'), images: [u('cdn.shopify.com/s/files/1/0997/6284/files/Colorfit_Pro_5.jpg')], description: 'Advanced Noise smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4013, title: 'boAt Wave Call 2', brand: 'boAt', category: 'smartwatches', price: 39, thumbnail: u('cdn.shopify.com/s/files/1/0057/8938/4802/files/Wave_Call_2.jpg'), images: [u('cdn.shopify.com/s/files/1/0057/8938/4802/files/Wave_Call_2.jpg')], description: 'Advanced boAt smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4014, title: 'Xiaomi Watch S3', brand: 'Xiaomi', category: 'smartwatches', price: 149, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/xiaomi-watch-s3.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/xiaomi-watch-s3.jpg')], description: 'Advanced Xiaomi smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 },
  { id: 4015, title: 'Samsung Galaxy Fit3', brand: 'Samsung', category: 'smartwatches', price: 199, thumbnail: u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-fit3.jpg'), images: [u('fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-fit3.jpg')], description: 'Advanced Samsung smartwatch.', discountPercentage: 18, rating: 4.5, stock: 200 }
]

export async function getCatalogProducts() {
  return customProducts
}

export async function getProducts(_req: Request, res: Response) {
  res.json({ products: customProducts })
}

export async function getProductById(req: Request, res: Response) {
  const id = Number(req.params.id)
  if (!Number.isFinite(id)) {
    res.status(400).json({ message: 'Invalid id' })
    return
  }
  const p = customProducts.find((x) => x.id === id)
  if (!p) {
    res.status(404).json({ message: 'Not found' })
    return
  }
  res.json({ product: p })
}
